name: Deploy PAMS app backend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker account
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t dnyaneshwarinchale/pams-backend .
      - name: Push image on docker hub
        run: docker push dnyaneshwarinchale/pams-backend:latest

  deploy:
    needs: build
    runs-on: Linux
    steps:
      - name: Pull image from docker hub
        run: docker pull dnyaneshwarinchale/pams-backend:latest
      - name: Remove existing docker container
        run: docker rm -f pams-backend
      - name: Run container
        run: docker run -d -p 8000:8000 --name pams-backend -e MONGO_URI='${{ secrets.MONGO_URI }}' -e JWT_SECRET='${{ secrets.JWT_SECRET }}'
